apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: giv-devops-dev
  labels:
    app: sonarqube-service
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: sonarqube
